import { Module } from '@nestjs/common';
import { MongooseModule } from '@nestjs/mongoose';

import {
  User,
  UserSchema,
  Group,
  GroupSchema,
  Course,
  CourseSchema,
  StudentCourse,
  StudentCourseSchema,
  EducatorCourse,
  EducatorCourseSchema,
  AdminCourse,
  AdminCourseSchema,
  Chapter,
  ChapterSchema,
  Quiz,
  QuizSchema,
  PracticeQuiz,
  PracticeQuizSchema,
  TimedQuiz,
  TimedQuizSchema,
  ExamQuiz,
  ExamQuizSchema,
  ScheduledQuiz,
  ScheduledQuizSchema,
  AdaptiveQuiz,
  AdaptiveQuizSchema,
  Question,
  QuestionSchema,
  FlashcardDeck,
  FlashcardDeckSchema,
  Flashcard,
  FlashcardSchema,
  BasicFlashcard,
  BasicFlashcardSchema,
  ClozeFlashcard,
  ClozeFlashcardSchema,
  ImageFlashcard,
  ImageFlashcardSchema,
  Enrollment,
  EnrollmentSchema,
  QuizAttempt,
  QuizAttemptSchema,
  FlashcardReview,
  FlashcardReviewSchema,
  UserFlashcardState,
  UserFlashcardStateSchema,
  Progress,
  ProgressSchema,
  ReminderSettings,
  ReminderSettingsSchema,
  RecommendationProfile,
  RecommendationProfileSchema,
  ActivityLog,
  ActivityLogSchema,
  DocumentUpload,
  DocumentUploadSchema,
} from './index';

@Module({
  imports: [
    MongooseModule.forFeature([
      { name: User.name, schema: UserSchema },
      { name: Group.name, schema: GroupSchema },
      { name: Course.name, schema: CourseSchema },
      { name: StudentCourse.name, schema: StudentCourseSchema },
      { name: EducatorCourse.name, schema: EducatorCourseSchema },
      { name: AdminCourse.name, schema: AdminCourseSchema },
      { name: Chapter.name, schema: ChapterSchema },
      { name: Quiz.name, schema: QuizSchema },
      { name: PracticeQuiz.name, schema: PracticeQuizSchema },
      { name: TimedQuiz.name, schema: TimedQuizSchema },
      { name: ExamQuiz.name, schema: ExamQuizSchema },
      { name: ScheduledQuiz.name, schema: ScheduledQuizSchema },
      { name: AdaptiveQuiz.name, schema: AdaptiveQuizSchema },
      { name: Question.name, schema: QuestionSchema },
      { name: FlashcardDeck.name, schema: FlashcardDeckSchema },
      { name: Flashcard.name, schema: FlashcardSchema },
      { name: BasicFlashcard.name, schema: BasicFlashcardSchema },
      { name: ClozeFlashcard.name, schema: ClozeFlashcardSchema },
      { name: ImageFlashcard.name, schema: ImageFlashcardSchema },
      { name: Enrollment.name, schema: EnrollmentSchema },
      { name: QuizAttempt.name, schema: QuizAttemptSchema },
      { name: FlashcardReview.name, schema: FlashcardReviewSchema },
      { name: UserFlashcardState.name, schema: UserFlashcardStateSchema },
      { name: Progress.name, schema: ProgressSchema },
      { name: ReminderSettings.name, schema: ReminderSettingsSchema },
      { name: RecommendationProfile.name, schema: RecommendationProfileSchema },
      { name: ActivityLog.name, schema: ActivityLogSchema },
      { name: DocumentUpload.name, schema: DocumentUploadSchema },
    ]),
  ],
  exports: [MongooseModule],
})
export class ModelsModule {}
